# Branchs to build
branches:
  only:
    - master 
    
image: Visual Studio 2019
configuration: Release

build:
  project: Snippeter.sln
  verbosity: minimal

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  # Increment version in .vsixmanifest and update the AppVeyor build version to match
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  
build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  # Push artifacts and publish the nighly build to http://vsixgallery.com
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
